name: Bridge APKs from Drive to Release
on: 
  workflow_dispatch:

jobs:
  upload_assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install gdown
        run: pip install gdown

      - name: Download Universal APK
        run: gdown "11Or4J855752rY_gqSCfQU2VzPm1S0Cq3" -O VOID-v9.13.26_universal_release.apk

      - name: Download arm64-v8a APK
        run: gdown "1xZ7zi3yiq-p53ayqTnJTQZHFCxZEHRqn" -O VOID-v9.13.26_arm64-v8a_release.apk

      - name: Download armeabi-v7a APK
        run: gdown "1vqiigb1RCaChVa0hBcNU1vQ8OZna2ory" -O VOID-v9.13.26_armeabi-v7a_release.apk

      - name: Upload to Draft Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload v9.13.26 VOID-v9.13.26_universal_release.apk VOID-v9.13.26_arm64-v8a_release.apk VOID-v9.13.26_armeabi-v7a_release.apk --clobber
